export const {
  DOC,
  WIN,
  HTMLBODY,
  BODY,
  OUT,
  OVERLAY,
  ACTIVE,
  INIT,
  OPEN,
  SHOW,
  ANIMATE,
  HAS_FLEX,
  PLAYED,
  PAUSED,
  BTN_MENU,
  HIDDEN,
  FIXED,
  SECTION,
  widthSM,
  widthMD,
  widthLG,
  slickXS,
  slickSM,
  slickMD,
} = {
  DOC: $(document),
  WIN: $(window),
  HTMLBODY: $('html, body'),
  BODY: $('body'),
  OUT: $('.out'),
  OVERLAY: $('.js-overlay'),
  ACTIVE: 'is-active',
  INIT: 'is-init',
  OPEN: 'is-open',
  SHOW: 'is-show',
  ANIMATE: 'is-animate',
  HAS_FLEX: 'has-flex',
  PLAYED: 'is-played',
  PAUSED: 'is-paused',
  BTN_MENU: $('.js-btn-menu'),
  HIDDEN: 'is-hidden',
  FIXED: 'is-fixed',
  SECTION: $('.js-section'),
  widthSM: 767,
  widthMD: 1023,
  widthLG: 1279
};
